import { Injectable } from '@nestjs/common';
import { AUTH_ERROR_MESSAGES } from '../auth.errors';

@Injectable()
export class AuthErrorMessageUtil {
  readonly INVALID_CREDENTIALS = AUTH_ERROR_MESSAGES.INVALID_CREDENTIALS;
  readonly INVALID_REFRESH_TOKEN = AUTH_ERROR_MESSAGES.INVALID_REFRESH_TOKEN;
  readonly INVALID_ACCESS_TOKEN = AUTH_ERROR_MESSAGES.INVALID_ACCESS_TOKEN;
  readonly INVALID_VALIDATION_CODE = AUTH_ERROR_MESSAGES.INVALID_VALIDATION_CODE;
  readonly CODE_EXPIRED = AUTH_ERROR_MESSAGES.CODE_EXPIRED;
  readonly ACCOUNT_INACTIVE = AUTH_ERROR_MESSAGES.ACCOUNT_INACTIVE;
  readonly EMAIL_NOT_VERIFIED = AUTH_ERROR_MESSAGES.EMAIL_NOT_VERIFIED;
  readonly EMAIL_ALREADY_VERIFIED = AUTH_ERROR_MESSAGES.EMAIL_ALREADY_VERIFIED;
  readonly USER_NOT_FOUND = AUTH_ERROR_MESSAGES.USER_NOT_FOUND;
  readonly EMAIL_ALREADY_EXISTS = AUTH_ERROR_MESSAGES.EMAIL_ALREADY_EXISTS;
  readonly USERNAME_ALREADY_EXISTS = AUTH_ERROR_MESSAGES.USERNAME_ALREADY_EXISTS;
  readonly STORE_NOT_FOUND = AUTH_ERROR_MESSAGES.STORE_NOT_FOUND;
  readonly NOT_STORE_MEMBER = AUTH_ERROR_MESSAGES.NOT_STORE_MEMBER;
}
